name: places_service
description: A service that makes it easy to get information from the Places Api
version: 0.1.4+7
homepage: https://filledstacks.com

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # data models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  geolocator: ^13.0.2
  flutter_google_maps_webservices: ^1.1.1
  uuid: ^4.5.1
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

  # data models
  freezed: ^3.0.3
  json_serializable: ^6.9.4

